[package]
name = "salat_mv"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
confy = "0.5.1"
serde = { version = "1.0.151", features = ["derive"] }
signal-hook = "0.3.14"
